version: '3'

services:
  minio1:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - C:\Users\Pras\OneDrive\My-Project\Gallery\minio\data:/data #change to your path folder
    environment:
      MINIO_ROOT_USER: "ROOTUSER"
      MINIO_ROOT_PASSWORD: "CHANGEME123"
    command: server /data --console-address ":9001"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
